version: "3.7"

services:
  mysql:
    image: mysql:5.7
    volumes:
      - type: bind
        source: ./mysql/config
        target: /etc/mysql/conf.d
    container_name: qvotech_box_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    env_file:
      - ./.env
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
