version: "3.1"

services:
  pg:
    image: postgres:${PG_VERSION}
    container_name: pg_db
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - dev-network
    ports:
      - "${PG_PORT}:${PG_PORT}"
    env_file:
      - ./.env
    volumes:
      - ./data/postgres/pgdata:/var/lib/postgresql/data/pgdata

networks:
  dev-network:
    driver: bridge

volumes:
  postgres_data:
