version: "3"

services:
  db:
    container_name: postgis_db
    image: kartoza/postgis:latest
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DBNAME: ${PG_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${PG_PORT}:${PG_PORT}"
    volumes:
      - ./data/postgres/pgdata:/var/lib/postgresql/data/pgdata
    networks:
      - postgis-network

networks:
  postgis-network:

volumes:
  postgres_data:
