version: "3.1"

services:
    redis:
        container_name: redis_rd
        image: redis:${REDIS_VERSION}
        command: redis-server --requirepass ${REDIS_PASSWORD}
        ports:
          - "${REDIS_PORT}:${REDIS_PORT}"
        networks:
          - docker-stack_dev-network

networks:
    docker-stack_dev-network:
        external: true
