version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_db
    volumes:
      - ./data/mysql:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    env_file:
      - ./.env
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    networks:
      - docker-stack_dev-network

networks:
  docker-stack_dev-network:
    external: true
